### ISSUE TITLE
Build error for 1.0.1c

### ISSUE THREAD

**Issue by varnav** [xvtom/build-openssl-android#4]
Trying to build 1.0.1c but getting an error:

```
../libcrypto.so: error: undefined reference to 'ERR_load_COMP_strings'
collect2: error: ld returned 1 exit status
```

**Comment by varnav** [comment]
Seems that -no-comp option breaks build of recent OpenSSL versions. 

https://github.com/openssl/openssl/issues/542

Fix is to remove '-no-comp' at line 49.

**Comment by appapurapu** [comment]
excellent. 
Fixed the openssl compilation issue after removing the -no-comp from configure options. 
For example, below command 

./config shared no-ssl2 no-ssl3 no-hw no-engine --openssldir=./output/android-21/
